### PR TITLE
BAAS-20636: remove method from session interface

### PR DESCRIPTION
**Pull request by nickpoindexter**

### CODE REVIEW

**Comment by kpatel71716** [comment]
Repasting on this PR: LGTM conceptually but have a question first. Is there a good way we don't accidentally pull this back in when we upgrade the driver. It might be something that could be easily glossed over.

We would probably catch this in baas tests because we no longer mock the interface but hoping we can catch it before that. Ideally the go-driver team just removes this if it has no value

**Review by tsedgwick — APPROVED** [review]
LGTM, can you drop the go-driver ticket in a comment before merging so we can track it to know if we can eventually remove this from the fork?

**Review by kpatel71716 — APPROVED** [review]
LGTM after reconsidering since I don't think the above is a large concern. I don't foresee too many updates on this version before a future major version upgrade to 2.x+ assuming the focus is on that upgrade. We will know if anything breaks because of our baas tests

**Comment by nickpoindexter** [comment]
Filed a [GODRIVER](https://jira.mongodb.org/browse/GODRIVER-2785) ticket for them to do this on the main repo

**Pull request merged**
